# Generated by Django 4.1.2 on 2022-10-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='asin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='monitoring.asin'),
        ),
    ]
